## This file is copied by "mix.R" from "grade-tpl.txt" to "grade.R" in "mix.R" output dir
## "grade.R" reads "<course>-answers" and "<course>-quests" dirs and generates "<course>-results"
## "grade.R" and "<course>-quests" are generated by "mix.R" in its output dir;
## "<course>-answers" should be manually copied from Emacs server share to "mix.R" output dir

## WARNING "grade.R" is overwritten by "grade-tpl.txt"
## if you modify "grade.R" for testing, copy it to "grade-tpl.txt" 

## Customise
SHOWGGRID <- FALSE  ## summary grid at PDF bottom


library(xtable)

main <- function(){

    ## Backup me in my grandparent
    backup.me()
    
    ## List ans dirs named as quest dirs
    ds <- sub("-answers$", "",  Sys.glob("*-answers"))
    ansdirs <- setNames(lapply(ds, function(d){
        q <- paste0(d, "-quests")
        a <- paste0(d, "-answers")
        ## There should be an quest dir for any ans dir
        if(!dir.exists(q)) stop("There is dir ", a, " but no dir ", q)
        setNames(a, q)}), ds)

    ## Course loop
    x <- lapply(ansdirs, function(ansd){

        ## Get course names
        course <- sub("-answers$", "",  ansd)

        ## Load "sols" list, "hlines", "flines" vectors
        ##   sols: per-exam list with student quests and sol grid
        ##   preamble, hlines, flines: course LaTeX header/footer 
        load(paste0(names(ansd), "/", course, "-sols.RData"))

        message("\nProcessing ", course, ": ", length(sols))
        
        ## List answer files 
        afiles <- Sys.glob(paste0(ansd, "/", course, "-ans-*.txt"))        

        ## Get answers: each seat a data frame in a list       
        #A <- lapply(x, read.table, sep=":", quote="", as.is=TRUE)
        A <- parseAnswers(afiles, A)

        ## Get student names
        contacts <- sapply(A, function(a)
           paste( a["given-name",], a["family-name",], a["student-id",]))
	   ## paste( a["given-name",], a["family-name",], a["student-id",], a["student-birth",]))

        ## Extract exams IDs 
        examids <- sapply(A, `[`, "exam-id", )

        ## Consistency
        x <- which(examids=="nil")
        NOID <- ""
        if(length(x)>0) {
            NOID <- lapply(x, function(xi) paste("WARNING: Missing exam ID for", contacts[xi]))
            examids <- examids[-x]
        }
        
        ## Calculate grades
        grades <- lapply(examids, function(examid){
            ans <- A[[examid]]
            sol <- sols[[examid]]$quests.sol
            grade(ans, sol)            
        })                

        ## Assign grades to questions
        gquests <- lapply(examids, function(examid){
            grade2quest(sols[[examid]]$quests, grades[[examid]])
        })

        ## Fill the header with score and contact details 
        hlines.id <- lapply(examids, function(examid){
            header.exam(hlines, contacts[examid], grades[[examid]] )})

        ## Fill the footer with score grid (only for SHOWGGRID true)
        flines.id <- lapply(examids, function(examid){
            sgrid2footer(flines, grades[[examid]])})

        
        ## Create result PDFs
        resdir <- paste0(course, "-results")
        createDir(resdir)
        x <- sapply(examids, function(examid){paste(contacts[[examid]], grades[[examid]]$score)})
        fcon <- file(paste0(resdir, "/grades.txt"), encoding="UTF-8")
        writeLines(x, fcon)
        close(fcon)
        lapply(examids, function(examid){
                    browser()

            message(which(examids==examid), " -> ", examid)

            footer=ifelse(SHOWGGRID, flines.id[[examid]], "\\end{questions}\n")

                    buildPdf(resdir, course, examid, gquests[[examid]],
                             preamble=preamble,                             
                             header=hlines.id[[examid]],
                             footer=footer,
                             libparent=names(ansd), combo=FALSE)
        })

        ## Build combo
        buildPdf(resdir, course, examid,
                 gquest=NULL,                 
                 preamble=preamble,
                 header=preamble,
                                        #header=split.preamble(hlines)[[1]],
                 footer=NULL,
                 libparent=names(ansd), combo=TRUE)

        ## Inform of unusable tests
        message(paste(NOID, collapse="\n"))

    }) ## end Course loop
} ## ===== end main

sgrid2footer <- function(# Fill the header with score
                         flines,   # Course header lines
                         grades    # Student details 
                            ){

    flines <- sub("\\\\end\\{document\\}", "", flines)
    #flines <-
        paste(flines, print(xtable(grades$grid), floating=FALSE, print.results=FALSE))
    ## paste(flines, "\n\n\\end{document}\n")
}


header.exam <- function( # Replace first fbox with Exam specific header with contact details and score
                            hlines,  # Course header lines
                            contact, # Student details 
                            grades   # Student score
                            ){
    
    x <- getfbox(hlines)
    hlines <- x$hlines
    boxpos <- x$fbox

    ## Create fbox
    fbox <- "\\fbox{\\parbox{\\textwidth}{"
    ## Add contact data
    fbox <- c(fbox, paste(contact, "\\quad\\today"))
    ## Add score
    fbox <- c(fbox, sprintf("\\\\Score: $%g$ (Good: %g, Wrong: %g)",
                              grades$score, grades$good, grades$bad))   
    fbox <- c(fbox, "}}")

    (hlines <- c(hlines[1:(boxpos-1)], fbox, hlines[(boxpos+1):length(hlines)]))
    
    #namer <- grep("^ *Full +name +and +signature:", hlines)
    #todayr <- grep("^ *Today +is +\\(",  hlines)
    #hlines[namer] <- paste(contact, "\\quad\\today")
    #hlines <- hlines[-((namer+1):todayr)]
    # 
    ### Add score
    #scorer <- grep("^ *Score", hlines)
    #hlines[scorer] <- sprintf("Score: $%g$ (Good: %g, Wrong: %g)",
    #                          grades$score, grades$good, grades$bad)
    #hlines
    
}

getfbox  <- function(hlines){
    ## Get begin/end of LaTeX \fbox in the quiz header,
    ## whose content is to be replaced with contact details and score

    match  <- regexpr("\\\\fbox *\\{", hlines)
    boxrow <- which(match>0)[1]
    if(is.na(boxrow)) error("Missing \\fbox to be replaced with score and contact data.")
    boxchar.s <- match[boxrow]
    boxchar.e <- attr(match, "match.length")[boxrow]
    boxrow.bak <- hlines[boxrow]
    hlines[boxrow] <- substring(boxrow.bak,  boxchar.s + boxchar.e)

    end <- NA
    np <- 0
    n <- boxrow-1
    while(is.na(end)){
        n <- n + 1                
        pos <- gregexpr("\\{|\\}", hlines[n])
        m <- regmatches(hlines[n], pos)[[1]]
        m[m=="{"] <- -1
        m[m=="}"] <- 1
        m <- as.integer(m)
        end <- which(cumsum(m)+np ==1)[1]
        np <-  sum(np, m)
    }

    hlines <- c(hlines[1:boxrow], "", hlines[n:length(hlines)])        
    hlines[boxrow] <- substring(boxrow.bak, 0, boxchar.s -1)
    hlines[boxrow +2] <- substring(hlines[boxrow +2],  pos[[1]][end] +1)
    list(hlines=hlines, fbox=boxrow +1) 
}

grade2quest <- function( # Return questions with grade after \question tag
                        quests,  # questions of n-th exam/student 
                        grades   # grades of n-th exam/student
                        ){
    
    lapply(seq_along(quests), function(i){
        q <- quests[[i]]             # i-th quest
        a <- grades$grid[["ans"]][i] # i-th ans
        a <- sprintf("\\textbf{(%s)}", toupper(a))
        q[1] <- paste(q[1], a)       # first quest
        q
    })        
}


createDir <- function(dirpath){ # Create output dir
    if(dir.exists(dirpath)) unlink(dirpath, recursive=TRUE)
    if(dir.exists(dirpath)) stop("Unable to delete directory ", dirpath)
    dir.create(dirpath)
    if(!dir.exists(dirpath)) stop("Unable to create directory ", dirpath)
}

plat <- function( # Path with proper slash for shell commands
                 pt){if(.Platform$OS.type=="windows") gsub("/", "\\\\", pt) else pt}

buildPdf <- function( # Build PDF with scores
                     resdir,         # result dir
                     coursename,     # 
                     examid,         # 
                     gquests,        # graded questions
                     preamble,       # LaTeX premable (inclding \begin{document})
                     header, footer, # LaTeX pre-quesitons header and footer
                     libparent,      # parent of local LaTeX libs directory
                     combo           # build combo? 
                     ){

                  browser()


    ## Combo file paths 
    fstem.c <- paste0(resdir, "/!", coursename, "-combo")
    ftex.c <- paste0(fstem.c, "-body.tex")
    ftex.c.con <- file(ftex.c, encoding="UTF-8", open="a") # append exams to body
    
    if(combo) {

        ## Build the combo
        footer <- "\n\n\\end{document}\n" # newpage 
        cat(footer, file=ftex.c.con, sep="\n", append=TRUE) # append footer to body
        ftex <- paste0(fstem.c, ".tex") # make final combo path
        ftex.con <- file(ftex, encoding="UTF-8") 
        writeLines(header, ftex.con) 
        file.append(ftex, ftex.c)
        
    } else {

        fstem <- paste0(resdir, "/", coursename, "-v", examid)    
        ftex <- paste0(fstem, ".tex")
        ftex.con <- file(ftex, encoding="UTF-8")        

        ## Save tex file with grades
        lines.body <- c(header, unlist(gquests))
        lines <- c(preamble, lines.body, footer, "\n\n\\end{document}\n")        
        writeLines(lines, ftex.con)

        ## Append to combo tex file        
        footer <- "\n\n\\end{questions}\n\\newpage" # newpage 
        cat(c(lines.body, footer), file=ftex.c.con, sep="\n", append=TRUE)
        
    }

    ## Clean
    close(ftex.c.con)
    close(ftex.con)

    
    ## Build PDF
    libs <- paste0("--include-directory=", plat(libparent))
    nout <- plat(dirname(ftex))
    ntex <- plat(ftex)
    ags =paste0(libs, " -halt-on-error -output-directory=", nout, " ", ntex)
    ret=system2("pdflatex", ags, stdout=TRUE, stderr=TRUE)
    if(!is.null(attr(ret, "status"))) stop("pdflatex gave: ", paste(ret, collapse="\n"))
    ## Second build
    ret=system2("pdflatex", ags, stdout=TRUE, stderr=TRUE)
    if(!is.null(attr(ret, "status"))) stop("pdflatex gave: ", paste(ret, collapse="\n"))

    ## Clean up
    if(combo) {
        ff <- Sys.glob(paste0(fstem.c, "*"))
        x <- grep("\\.pdf$", ff)
        unlink(ff[-x])
    } else {
        ff <- Sys.glob(paste0(fstem, ".*"))
        x <- grep("\\.pdf$", ff)
        unlink(ff[-x])
    }
}


parseAnswers <- function(## parse answer files as a list whose names are seats,
                         ## each seat element is data frame with fields by row
                         afiles, # answer file paths (containing seats)
                         adata   # list where each elt is the file content
                         ){
    
    ## Read answers and 
    adata <- lapply(afiles, readAnswers)

    ## Add seat 
    seats <- tools:::file_path_sans_ext(basename(afiles))
    seats <- sub("^.+-ans-", "", seats)
    adata <- mapply(function(stud, seat){
        rbind(data.frame(Student=seat, row.names="seat", stringsAsFactors=FALSE), stud)},
        adata, seats, SIMPLIFY=FALSE)

    ## Name answers after exam IDs
    examids <- sapply(adata, `[`, "exam-id", )
    setNames(adata, examids)
}
  

readAnswers <- function(af){ # Read and preformat answer files 

    lines <- readLines(af, warn=FALSE, encoding="UTF-8")
    stud <- sapply(regmatches(lines, regexec("(.+?):(.+)", lines)),
                   function(l) setNames(l[3],l[2]))
    stud <- as.data.frame(stud, stringsAsFactors=FALSE, nm="Student")

    ## Trim spaces and sanitize
    stud[,1] <- trimws(stud[,1])
    stud[,1] <- sanitize(stud[,1])
    stud["ans-string",] <- gsub('"', '', stud["ans-string",]) # no quotes
    stud    
}


parseAnswers.old <- function(## parse answer files as a list whose names are seats,
                         ## each seat element is data frame with fields by row
                         afiles, # answer file paths (containing seats)
                         adata   # list where each elt is the file contents
                         ){
    
    ## Extract seats from path
    seats=tools:::file_path_sans_ext(basename(afiles))
    seats=sub("^.+-ans-", "", seats)

    ## For each answer set fields as DF rows 
    adata=lapply(adata, function(a) {
            x=a[,2, drop=FALSE]
            row.names(x) =a[[1]]
            names(x)="Student"
            x[,1]=trimws(x[,1])
            x[,1] <- sanitize(x[,1])
            x["ans-string",] <- gsub('"', '', x["ans-string",])
            x})

    ## Add seat field to DF rows 
    adata <- lapply(seq_along(seats), function(i) {
        x <- rbind(seats[i],adata[[i]])
        row.names(x)[1] <-  "seat"
        x
    })

    ## Name DF in the list by exam ID
    examids <- sapply(adata, `[`, "exam-id", )
    setNames(adata, examids)    
}
                         
grade <- function( # Grade the answer vector
                  ans, # i-th answers
                  sol  # i-th solution sub-list
                  ){

    ## get related sols ans weights 
    s=sol$sol
    w=sol$weight

    ## Get answer letters
    al=ans["ans-string",]
    al=strsplit(al, " ")[[1]]

    ## Vector by type of answers 
    good <- as.integer(s==al)    # 1 if good: sum(good)
    nil <- as.integer("nil"!=al) # 0 if nil:  sum(-nil+1)
    bad  <- as.integer(s!=al)    # 1 if non-good: nil %*% bad or sum(bad) - sum(-nil+1)
    list(score=good %*% w - nil %*% bad, good=sum(good), bad=nil %*% bad,
         grid=data.frame(ans=al, sol=s, weight=w, stringsAsFactors=FALSE))
}

sanitize <-  function(s){ # LaTeX safe chars
    first <- "]["
    legal <- "!@*()+-=;',./`:?\" "
    pat <- paste0(first, "[:alnum:]", legal)
    pat <- paste0("[^", pat, "]")
    s <- gsub(pat, "", s)
    gsub("@", "$@$~", s)        
}
    
backup.me <- function()
    ## During testing it is convenent to modify "grade.R" rather than its template;
    ## but mix.R might overwrite "grade.R" parent, so a backup is made in the grandparent
    file.copy("grade.R", "./../grade.R.bak", overwrite=TRUE) 

## not used
split.preamble <- function(lines){
    ## Given lines char vector, return a list, where
    ## the first element is the preamble + begin{document}
    ## the second element is the remaining lines
    ## Assumes \begin{document} is assumed on a single line

    x=grep("^\\s*\\\\begin\\s*\\{document\\}", lines)
    preamble <- lines[1:x]
    lines <- lines[-(1:x)] # after begin document
    list(preamble, lines)
}

